/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Check API and database health */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Log in with the shared admin password */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Clear the session cookie */
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get the current session's user, if any */
        get: operations["getCurrentUser"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/players": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List players */
        get: operations["listPlayers"];
        put?: never;
        /** Create a player (requires admin role) */
        post: operations["createPlayer"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/players/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a player profile */
        get: operations["getPlayer"];
        put?: never;
        post?: never;
        /** Delete a player who has never played a match (requires admin role) */
        delete: operations["deletePlayer"];
        options?: never;
        head?: never;
        /** Update a player (requires admin role) */
        patch: operations["updatePlayer"];
        trace?: never;
    };
    "/players/{id}/rating-history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a player's rating history */
        get: operations["getPlayerRatingHistory"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/players/{id}/matches": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List a player's matches, cursor-paginated */
        get: operations["listPlayerMatches"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/matches/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Preview a match outcome without recording it (requires recorder role) */
        post: operations["previewMatch"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/matches": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List matches, cursor-paginated */
        get: operations["listMatches"];
        put?: never;
        /** Record a match result (requires recorder role); idempotent on id */
        post: operations["recordMatch"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/matches/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a single match and its adjustment history */
        get: operations["getMatch"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/matches/{id}/void-preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Preview the ratings/ranks that would result from voiding a match, without voiding it (requires admin role) */
        get: operations["previewVoidMatch"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/matches/{id}/void": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Void a match (requires admin role) */
        post: operations["voidMatch"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/matches/{id}/correct": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Correct a match (requires admin role) */
        post: operations["correctMatch"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/leaderboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get the leaderboard (latest session by default) */
        get: operations["getLeaderboard"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List sessions */
        get: operations["listSessions"];
        put?: never;
        /** Open a new session (requires recorder role) */
        post: operations["openSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions/current": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get the currently open session, if any (204 if none) */
        get: operations["getCurrentSession"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a session summary */
        get: operations["getSessionSummary"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Rename a session (requires recorder role) */
        patch: operations["renameSession"];
        trace?: never;
    };
    "/sessions/{id}/close": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Close a session (requires recorder role) */
        post: operations["closeSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/rating-configs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List rating configs (requires admin role) */
        get: operations["listRatingConfigs"];
        put?: never;
        /** Create a rating config (requires admin role) */
        post: operations["createRatingConfig"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/rating-configs/{id}/rebuild": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Rebuild rating snapshots for a config by replaying matches (requires admin role) */
        post: operations["rebuildRatingConfig"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/rating-configs/{id}/leaderboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Preview the leaderboard a rating config would produce (requires admin role) */
        get: operations["getRatingConfigLeaderboard"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: never;
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Default Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {string} */
                        status: "ok";
                        /** @enum {string} */
                        db: "ok";
                    };
                };
            };
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    password: string;
                };
            };
        };
        responses: {
            /** @description Default Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        user: {
                            id: string;
                            name: string;
                            /** @enum {string} */
                            role: "admin" | "recorder" | "viewer";
                        };
                    };
                };
            };
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Default Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getCurrentUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Default Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        user: {
                            id: string;
                            name: string;
                            /** @enum {string} */
                            role: "admin" | "recorder" | "viewer";
                        };
                    };
                };
            };
            /** @description Default Response */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        type: string;
                        title: string;
                        status: number;
                        detail?: string;
                        instance?: string;
                    } & {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    listPlayers: {
        parameters: {
            query?: {
                active?: "true" | "false";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Default Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        id: string;
                        name: string;
                        avatarUrl: string | null;
                        isActive: boolean;
                        /** Format: date-time */
                        createdAt: string;
                        lastPlayedAt: string | null;
                    }[];
                };
            };
        };
    };
    createPlayer: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    name: string;
                    /** Format: uri */
                    avatarUrl?: string;
                };
            };
        };
        responses: {
            /** @description Default Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        id: string;
                        name: string;
                        avatarUrl: string | null;
                        isActive: boolean;
                    };
                };
            };
        };
    };
    getPlayer: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Default Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        playerId: string;
                        name: string;
                        isActive: boolean;
                        /** Format: date-time */
                        createdAt: string;
                        rating: number;
                        gamesPlayed: number;
                        wins: number;
                        draws: number;
                        losses: number;
                        form: ("W" | "L" | "D")[];
                        streak: {
                            /** @enum {string} */
                            result: "W" | "L" | "D";
                            length: number;
                        } | null;
                        bestStreak: {
                            /** @enum {string} */
                            result: "W" | "L" | "D";
                            length: number;
                        } | null;
                        goalsFor: number;
                        goalsAgainst: number;
                        isProvisional: boolean;
                    };
                };
            };
        };
    };
    deletePlayer: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Default Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    updatePlayer: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    name?: string;
                    avatarUrl?: string | null;
                    isActive?: boolean;
                };
            };
        };
        responses: {
            /** @description Default Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        id: string;
                        name: string;
                        avatarUrl: string | null;
                        isActive: boolean;
                    };
                };
            };
        };
    };
    getPlayerRatingHistory: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Default Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        matchId: string;
                        sequence: number;
                        /** Format: date-time */
                        playedAt: string;
                        before: number;
                        after: number;
                        delta: number;
                    }[];
                };
            };
        };
    };
    listPlayerMatches: {
        parameters: {
            query?: {
                cursor?: number;
                limit?: number;
            };
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Default Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: {
                            id: string;
                            sequence: number;
                            homePlayerId: string;
                            awayPlayerId: string;
                            homeScore: number;
                            awayScore: number;
                            isVoid: boolean;
                        }[];
                        nextCursor: number | null;
                    };
                };
            };
        };
    };
    previewMatch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    homePlayerId: string;
                    awayPlayerId: string;
                    homeScore: number;
                    awayScore: number;
                    sessionId?: string;
                };
            };
        };
        responses: {
            /** @description Default Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        home: {
                            playerId: string;
                            before: {
                                rating: number;
                                gamesPlayed: number;
                            };
                            after: {
                                rating: number;
                                gamesPlayed: number;
                            };
                            expectedScore: number;
                            actualScore: 1 | 0.5 | 0;
                            delta: number;
                            wasProvisional: boolean;
                        };
                        away: {
                            playerId: string;
                            before: {
                                rating: number;
                                gamesPlayed: number;
                            };
                            after: {
                                rating: number;
                                gamesPlayed: number;
                            };
                            expectedScore: number;
                            actualScore: 1 | 0.5 | 0;
                            delta: number;
                            wasProvisional: boolean;
                        };
                        upset: boolean;
                    };
                };
            };
        };
    };
    listMatches: {
        parameters: {
            query?: {
                cursor?: number;
                limit?: number;
                sessionId?: string;
                playerId?: string;
                includeVoided?: "true" | "false";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Default Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: {
                            id: string;
                            sequence: number;
                            homePlayerId: string;
                            awayPlayerId: string;
                            homeScore: number;
                            awayScore: number;
                            isVoid: boolean;
                            /** Format: date-time */
                            playedAt: string;
                            sessionId: string | null;
                            recordedBy: string;
                            /** Format: date-time */
                            recordedAt: string;
                            decidedOnPenalties: boolean;
                            outcome: {
                                home: {
                                    playerId: string;
                                    before: {
                                        rating: number;
                                        gamesPlayed: number;
                                    };
                                    after: {
                                        rating: number;
                                        gamesPlayed: number;
                                    };
                                    expectedScore: number;
                                    actualScore: 1 | 0.5 | 0;
                                    delta: number;
                                    wasProvisional: boolean;
                                };
                                away: {
                                    playerId: string;
                                    before: {
                                        rating: number;
                                        gamesPlayed: number;
                                    };
                                    after: {
                                        rating: number;
                                        gamesPlayed: number;
                                    };
                                    expectedScore: number;
                                    actualScore: 1 | 0.5 | 0;
                                    delta: number;
                                    wasProvisional: boolean;
                                };
                                upset: boolean;
                            } | null;
                        }[];
                        nextCursor: number | null;
                    };
                };
            };
        };
    };
    recordMatch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** Format: uuid */
                    id: string;
                    homePlayerId: string;
                    awayPlayerId: string;
                    homeScore: number;
                    awayScore: number;
                    decidedOnPenalties?: boolean;
                    /** Format: date-time */
                    playedAt?: string;
                    sessionId?: string;
                };
            };
        };
        responses: {
            /** @description Default Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        match: {
                            id: string;
                            sequence: number;
                            homePlayerId: string;
                            awayPlayerId: string;
                            homeScore: number;
                            awayScore: number;
                            decidedOnPenalties: boolean;
                            /** Format: date-time */
                            playedAt: string;
                            sessionId: string | null;
                            recordedBy: string;
                        };
                        outcome: {
                            home: {
                                playerId: string;
                                before: {
                                    rating: number;
                                    gamesPlayed: number;
                                };
                                after: {
                                    rating: number;
                                    gamesPlayed: number;
                                };
                                expectedScore: number;
                                actualScore: 1 | 0.5 | 0;
                                delta: number;
                                wasProvisional: boolean;
                            };
                            away: {
                                playerId: string;
                                before: {
                                    rating: number;
                                    gamesPlayed: number;
                                };
                                after: {
                                    rating: number;
                                    gamesPlayed: number;
                                };
                                expectedScore: number;
                                actualScore: 1 | 0.5 | 0;
                                delta: number;
                                wasProvisional: boolean;
                            };
                            upset: boolean;
                        };
                        rankChanges: {
                            playerId: string;
                            from: number;
                            to: number;
                        }[];
                    };
                };
            };
        };
    };
    getMatch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Default Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        match: {
                            id: string;
                            sequence: number;
                            homePlayerId: string;
                            awayPlayerId: string;
                            homeScore: number;
                            awayScore: number;
                            isVoid: boolean;
                            /** Format: date-time */
                            playedAt: string;
                            sessionId: string | null;
                            recordedBy: string;
                            /** Format: date-time */
                            recordedAt: string;
                            decidedOnPenalties: boolean;
                        };
                        adjustments: {
                            id: string;
                            matchId: string;
                            sequence: number;
                            /** @enum {string} */
                            type: "void" | "correct";
                            reason: string;
                            newHomePlayerId: string | null;
                            newAwayPlayerId: string | null;
                            newHomeScore: number | null;
                            newAwayScore: number | null;
                            adjustedBy: string;
                            /** Format: date-time */
                            adjustedAt: string;
                        }[];
                        outcome: {
                            home: {
                                playerId: string;
                                before: {
                                    rating: number;
                                    gamesPlayed: number;
                                };
                                after: {
                                    rating: number;
                                    gamesPlayed: number;
                                };
                                expectedScore: number;
                                actualScore: 1 | 0.5 | 0;
                                delta: number;
                                wasProvisional: boolean;
                            };
                            away: {
                                playerId: string;
                                before: {
                                    rating: number;
                                    gamesPlayed: number;
                                };
                                after: {
                                    rating: number;
                                    gamesPlayed: number;
                                };
                                expectedScore: number;
                                actualScore: 1 | 0.5 | 0;
                                delta: number;
                                wasProvisional: boolean;
                            };
                            upset: boolean;
                        } | null;
                    };
                };
            };
        };
    };
    previewVoidMatch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Default Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        matchId: string;
                        players: {
                            playerId: string;
                            ratingBefore: number;
                            gamesPlayedBefore: number;
                            ratingAfter: number;
                            gamesPlayedAfter: number;
                        }[];
                        rankChanges: {
                            playerId: string;
                            from: number;
                            to: number;
                        }[];
                    };
                };
            };
        };
    };
    voidMatch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    reason: string;
                };
            };
        };
        responses: {
            /** @description Default Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        match: {
                            id: string;
                            sequence: number;
                            homePlayerId: string;
                            awayPlayerId: string;
                            homeScore: number;
                            awayScore: number;
                            isVoid: boolean;
                        };
                        affectedPlayers: string[];
                    };
                };
            };
        };
    };
    correctMatch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    reason: string;
                    homePlayerId: string;
                    awayPlayerId: string;
                    homeScore: number;
                    awayScore: number;
                };
            };
        };
        responses: {
            /** @description Default Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        match: {
                            id: string;
                            sequence: number;
                            homePlayerId: string;
                            awayPlayerId: string;
                            homeScore: number;
                            awayScore: number;
                            isVoid: boolean;
                        };
                        affectedPlayers: string[];
                    };
                };
            };
        };
    };
    getLeaderboard: {
        parameters: {
            query?: {
                session?: "all-time" | string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Default Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        entries: {
                            rank: number;
                            playerId: string;
                            rating: number;
                            gamesPlayed: number;
                            wins: number;
                            draws: number;
                            losses: number;
                            winPct: number;
                            form: ("W" | "L" | "D")[];
                            streak: {
                                /** @enum {string} */
                                result: "W" | "L" | "D";
                                length: number;
                            } | null;
                            isProvisional: boolean;
                        }[];
                        meanRating: number;
                        ratingConfig: {
                            name: string;
                            provisionalGames: number;
                        };
                        session: {
                            id: string;
                            name: string;
                        } | null;
                    };
                };
            };
        };
    };
    listSessions: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Default Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        id: string;
                        name: string;
                        /** Format: date-time */
                        startedAt: string;
                        endedAt: string | null;
                        createdBy: string;
                    }[];
                };
            };
        };
    };
    openSession: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    name: string;
                };
            };
        };
        responses: {
            /** @description Default Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        id: string;
                        name: string;
                        /** Format: date-time */
                        startedAt: string;
                        endedAt: string | null;
                        createdBy: string;
                    };
                };
            };
        };
    };
    getCurrentSession: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Default Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        id: string;
                        name: string;
                        /** Format: date-time */
                        startedAt: string;
                        endedAt: string | null;
                        createdBy: string;
                    };
                };
            };
            /** @description Default Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getSessionSummary: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Default Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        id: string;
                        name: string;
                        /** Format: date-time */
                        startedAt: string;
                        endedAt: string | null;
                        matchCount: number;
                        playerDeltas: {
                            playerId: string;
                            delta: number;
                        }[];
                        biggestMover: {
                            playerId: string;
                            delta: number;
                        } | null;
                        upsetCount: number;
                    };
                };
            };
        };
    };
    renameSession: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    name: string;
                };
            };
        };
        responses: {
            /** @description Default Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        id: string;
                        name: string;
                        /** Format: date-time */
                        startedAt: string;
                        endedAt: string | null;
                        createdBy: string;
                    };
                };
            };
        };
    };
    closeSession: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Default Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        id: string;
                        name: string;
                        /** Format: date-time */
                        startedAt: string;
                        endedAt: string | null;
                        createdBy: string;
                    };
                };
            };
        };
    };
    listRatingConfigs: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Default Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        id: string;
                        name: string;
                        /** @enum {string} */
                        algorithm: "elo";
                        params: {
                            baseline: number;
                            kProvisional: number;
                            provisionalGames: number;
                            kEstablished: number;
                            /** @enum {number} */
                            drawScore: 0.5;
                            /** @default 400 */
                            expectationScale: number;
                            goalDifferenceFactor?: {
                                enabled: boolean;
                                /** @default 2 */
                                divisor: number;
                                /** @default 1.5 */
                                cap: number;
                            };
                            eliteK?: {
                                enabled: boolean;
                                /** @default 1500 */
                                enterAt: number;
                                /** @default 1450 */
                                exitAt: number;
                                k: number;
                                /** @default true */
                                requireEstablished: boolean;
                            };
                            repeatOpponentDamping?: {
                                enabled: boolean;
                                /** @default 3 */
                                threshold: number;
                                /** @default 0.85 */
                                factor: number;
                                /** @default 0.25 */
                                minMultiplier: number;
                            };
                            maxDelta?: number;
                            ratingFloor?: number;
                        };
                        isActive: boolean;
                    }[];
                };
            };
        };
    };
    createRatingConfig: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    name: string;
                    /** @enum {string} */
                    algorithm: "elo";
                    params: {
                        baseline: number;
                        kProvisional: number;
                        provisionalGames: number;
                        kEstablished: number;
                        /** @enum {number} */
                        drawScore: 0.5;
                        /** @default 400 */
                        expectationScale?: number;
                        goalDifferenceFactor?: {
                            enabled: boolean;
                            /** @default 2 */
                            divisor?: number;
                            /** @default 1.5 */
                            cap?: number;
                        };
                        eliteK?: {
                            enabled: boolean;
                            /** @default 1500 */
                            enterAt?: number;
                            /** @default 1450 */
                            exitAt?: number;
                            k: number;
                            /** @default true */
                            requireEstablished?: boolean;
                        };
                        repeatOpponentDamping?: {
                            enabled: boolean;
                            /** @default 3 */
                            threshold?: number;
                            /** @default 0.85 */
                            factor?: number;
                            /** @default 0.25 */
                            minMultiplier?: number;
                        };
                        maxDelta?: number;
                        ratingFloor?: number;
                    };
                };
            };
        };
        responses: {
            /** @description Default Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        id: string;
                        name: string;
                        /** @enum {string} */
                        algorithm: "elo";
                        params: {
                            baseline: number;
                            kProvisional: number;
                            provisionalGames: number;
                            kEstablished: number;
                            /** @enum {number} */
                            drawScore: 0.5;
                            /** @default 400 */
                            expectationScale: number;
                            goalDifferenceFactor?: {
                                enabled: boolean;
                                /** @default 2 */
                                divisor: number;
                                /** @default 1.5 */
                                cap: number;
                            };
                            eliteK?: {
                                enabled: boolean;
                                /** @default 1500 */
                                enterAt: number;
                                /** @default 1450 */
                                exitAt: number;
                                k: number;
                                /** @default true */
                                requireEstablished: boolean;
                            };
                            repeatOpponentDamping?: {
                                enabled: boolean;
                                /** @default 3 */
                                threshold: number;
                                /** @default 0.85 */
                                factor: number;
                                /** @default 0.25 */
                                minMultiplier: number;
                            };
                            maxDelta?: number;
                            ratingFloor?: number;
                        };
                        isActive: boolean;
                    };
                };
            };
        };
    };
    rebuildRatingConfig: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Default Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        configId: string;
                        matchCount: number;
                    };
                };
            };
        };
    };
    getRatingConfigLeaderboard: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Default Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        configId: string;
                        entries: {
                            playerId: string;
                            rating: number;
                            gamesPlayed: number;
                            rank: number;
                        }[];
                    };
                };
            };
        };
    };
}
